services:
  nextjs:
    container_name: admission-form-fe
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - NEXT_PUBLIC_FRAPPE_TOKEN=$NEXT_PUBLIC_FRAPPE_TOKEN
      - NEXT_PUBLIC_FRAPPE_TOKEN=$NEXT_PUBLIC_FRAPPE_TOKEN
    ports:
      - "3000:3000"
