name: 01.neo4j-graph-viewer

on:
  workflow_dispatch:
    inputs:
      confirmDeployment:
        description: 'Confirm Deployment'
        default: 'OK'
        required: true
env:
  IMAGE: neo4j-graph-viewer
  DOT_ENV_FILE_NAME: .env.neo4j-graph-viewer
  PORT: 4030
jobs:
  variables:
    name: setup variable
    runs-on: ubuntu-latest
    outputs:
      IMAGE: ${{ env.IMAGE }}
      DOT_ENV_FILE_NAME: ${{ env.DOT_ENV_FILE_NAME }}
      PORT: ${{ env.PORT }}
    steps:
      - name: Echo
        run: echo prepare variable
  neo4j-graph-viewer:
    needs: variables
    name: deploy neo4j-graph-viewer
    uses: ./.github/workflows/00.gke-deployment.yml
    with:
      IMAGE: ${{ needs.variables.outputs.IMAGE }}
      DOT_ENV_FILE_NAME: ${{ needs.variables.outputs.DOT_ENV_FILE_NAME }}      
      PORT: ${{ needs.variables.outputs.PORT }}    
    secrets:
      HARBOR_URL: ${{ secrets.HARBOR_URL }}
      HARBOR_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      HARBOR_PASSWORD: ${{ secrets.PASSWORD_DOCKER_HUB }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SERVER_IP: ${{ secrets.SERVER_IP }}
      SERVER_USER: ${{ secrets.SERVER_USER }}
